// <auto-generated />
namespace TrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class backtowhereIstartedbeginningofdaywithclassesintherightspotandgoogleapikeyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(backtowhereIstartedbeginningofdaywithclassesintherightspotandgoogleapikeyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031710428_back to where I started beginning of day, with classes in the right spot and google api key added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
