// <auto-generated />
namespace TrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatestorunapplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestorunapplication));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031427147_updates to run application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
