// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class workingonviewsandqueriestogetthemhowIwantdiscoveredissuewithforeignkeynotworkingcorrectly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workingonviewsandqueriestogetthemhowIwantdiscoveredissuewithforeignkeynotworkingcorrectly));
        
        string IMigrationMetadata.Id
        {
            get { return "201705081502389_working on views and queries to get them how I want, discovered issue with foreign key not working correctly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
