// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rolesworkinggoogleapikeyaddedtoconfigfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rolesworkinggoogleapikeyaddedtoconfigfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201705041242062_roles working - google api key added to config file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
