// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foreignkeytoApllicationUseronService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreignkeytoApllicationUseronService));
        
        string IMigrationMetadata.Id
        {
            get { return "201705041934558_foreign key to ApllicationUser on Service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
