// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingdatetimedatatypestofields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdatetimedatatypestofields));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051248513_adding datetime datatypes to fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
