// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tryingtonullifytheDateTimefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryingtonullifytheDateTimefields));
        
        string IMigrationMetadata.Id
        {
            get { return "201705042026194_trying to nullify the DateTime fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
