// <auto-generated />
namespace Trash_Collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedcontrollerandviewsforinvoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedcontrollerandviewsforinvoices));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051558339_removed controller and views for invoices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
